version: '3.7'

services:
  backend:
    build: ./backend
    image: backend:custom
    container_name: backend
    restart: unless-stopped
    entrypoint: /app/entrypoint.sh
    networks:
      - postgres_network
      - nginx_network
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    ports:
      - 8000:8000
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    image: frontend:custom
    container_name: frontend
    restart: unless-stopped
    networks:
      - postgres_network
      - nginx_network
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    ports:
      - 3000:3000
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    restart: unless-stopped
    networks:
      - postgres_network
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env.postgres      
  nginx:
    build: ./nginx
    image: nginx:custom
    container_name: nginx
    restart: unless-stopped
    networks:
      - nginx_network
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  postgres:
    external: true
  staticfiles:
    external: true
  mediafiles:
    external: true

networks:
  postgres_network:
    driver: bridge
  nginx_network:
    driver: bridge
