version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:13.1-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
  backend:
    container_name: backend
    image: backend:custom
    build: ./backend
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - backend:/usr/src/app/static
      - media:/usr/src/app/media
    env_file:
      - ./backend/.env
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - postgres
  frontend:
    container_name: frontend
    image: frontend:custom
    build: ./frontend
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - frontend:/usr/src/app/build/static
      - media:/usr/src/app/media
    env_file:
      - ./frontend/.env
    command: serve -s build -l 3000
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: nginx:custom
    build: ./nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - backend:/usr/src/app/backend
      - frontend:/usr/src/app/frontend
      - media:/usr/src/app/media
    depends_on:
      - frontend

volumes:
  postgres:
    external: true
  backend:
    external: true
  frontend:
    external: true
  media:
    external: true
